api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from api.views import CarsViewSet, MaintenanceViewSet, ReclamationViewSet

app_name = "api"

router = routers.DefaultRouter()

router.register(r"cars", CarsViewSet)
router.register(r"maintenance", MaintenanceViewSet)
router.register(r"reclamation", ReclamationViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Silant API",
        default_version="v1.0.0",
        description="obtaining data from the tables Cars, Maintenance, Reclamation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

urlpatterns += router.urls

app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.settings import DEBUG

handler403 = 'main.views.tr_handler403'
handler404 = 'main.views.tr_handler404'
handler500 = 'main.views.tr_handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('maintenance/', include('maintenance.urls', namespace='maintenance')),
    path('reclamation/', include('reclamation.urls', namespace='reclamation')),
    path('deskbook/', include('deskbook.urls', namespace='deskbook')),
    path('user/', include('users.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

deskbook/urls.py
from django.urls import path

from deskbook import views


app_name = 'deskbook'

urlpatterns = [

    path('service_company/', views.get_deskbook, name='service_company'),
    path('vehicle_model/', views.get_deskbook, name='vehicle_model'),
    path('engine_model/', views.get_deskbook, name='engine_model'),
    path('transmission_model/', views.get_deskbook, name='transmission_model'),
    path('drive_axle_model/', views.get_deskbook, name='drive_axle_model'),
    path('steering_axle_model/', views.get_deskbook, name='steering_axle_model'),
    path('failure_node/', views.get_deskbook, name='failure_node'),
    path('recovery_method/', views.get_deskbook, name='recovery_method'),
    path('view_maintenance/', views.get_deskbook, name='view_maintenance'),

    path('add_deskbook/<slug:slug>', views.add_deskbook, name='add_deskbook'),
    path('edit_deskbook/<slug:slug>/<int:item_id>', views.edit_deskbook, name='edit_deskbook'),
    path('remove_deskbook/<slug:slug>/<int:item_id>', views.remove_deskbook, name='remove_deskbook'),

    path('deskbook_ajax/', views.deskbook_ajax, name='deskbook_ajax'),
]

deskbook/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from django.core.exceptions import PermissionDenied
from django.core.paginator import EmptyPage, Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse

from deskbook.forms import (
    AddServiceCompany,
    AddDriveAxleForm,
    AddEngineForm,
    AddFailureNodeForm,
    AddRecoveryMethodForm,
    AddSteeringAxleForm,
    AddTransmissionForm,
    AddVehicleForm,
    AddViewMaintenanceForm,
)
from deskbook.forms import (
    EditServiceCompany,
    EditDriveAxleForm,
    EditEngineForm,
    EditFailureNodeForm,
    EditRecoveryMethodForm,
    EditSteeringAxleForm,
    EditTransmissionForm,
    EditVehicleForm,
    EditViewMaintenanceForm,
)
from deskbook.models import (
    ServiceCompany,
    FailureNode,
    RecoveryMethod,
    VehicleModel,
    EngineModel,
    TransmissionModel,
    DriveAxle,
    SteeringAxle,
    ViewMaintenance,
)


@login_required
def add_deskbook(request, slug):
    deskbook_add_permission = [f'deskbook.{el}' for el in Permission.objects.filter(
        content_type__app_label="deskbook", codename__startswith="add"
    ).values_list("codename", flat=True)]
    
    if not request.user.has_perms(deskbook_add_permission):
        raise PermissionDenied
    
    if request.method == "GET":
        path = request.META["HTTP_REFERER"]
        if slug == "service_company":
            form = AddServiceCompany()
        elif slug == "vehicle_model":
            form = AddVehicleForm()
        elif slug == "engine_model":
            form = AddEngineForm()
        elif slug == "transmission_model":
            form = AddTransmissionForm()
        elif slug == "drive_axle_model":
            form = AddDriveAxleForm()
        elif slug == "steering_axle_model":
            form = AddSteeringAxleForm()
        elif slug == "failure_node":
            form = AddFailureNodeForm()
        elif slug == "recovery_method":
            form = AddRecoveryMethodForm()
        elif slug == "view_maintenance":
            form = AddViewMaintenanceForm()

    elif request.method == "POST":
        path = request.POST.get("path_referer", None)
        if slug == "service_company":
            form = AddServiceCompany(data=request.POST)
        elif slug == "vehicle_model":
            form = AddVehicleForm(data=request.POST)
        elif slug == "engine_model":
            form = AddEngineForm(data=request.POST)
        elif slug == "transmission_model":
            form = AddTransmissionForm(data=request.POST)
        elif slug == "drive_axle_model":
            form = AddDriveAxleForm(data=request.POST)
        elif slug == "steering_axle_model":
            form = AddSteeringAxleForm(data=request.POST)
        elif slug == "failure_node":
            form = AddFailureNodeForm(data=request.POST)
        elif slug == "recovery_method":
            form = AddRecoveryMethodForm(data=request.POST)
        elif slug == "view_maintenance":
            form = AddViewMaintenanceForm(data=request.POST)

        if form.is_valid():
            form.save()
            messages.success(
                request,
                f"{request.user.username}, Вы успешно добавили запись в справочник!",
            )
            if path:
                return HttpResponseRedirect(path)
            else:
                return HttpResponseRedirect(reverse(f"deskbook:{slug}"))
        else:
            messages.warning(
                request, f"{request.user.username}, Вы неверно ввели данные!"
            )

    context = {
        "title": "Справочники",
        "form": form,
        "slug": slug,
        "path": path,
    }

    return render(request, "deskbook/add_deskbook.html", context=context)


@login_required
def get_deskbook(request):
    deskbook_view_permission = [f'deskbook.{el}' for el in Permission.objects.filter(
        content_type__app_label="deskbook", codename__startswith="view"
    ).values_list("codename", flat=True)]
    
    if not request.user.has_perms(deskbook_view_permission) or not request.user.user_role in ['MG', 'AD']:
        raise PermissionDenied
    
    page = request.GET.get("page", 1)

    if "service_company" in request.path:
        qs = ServiceCompany.objects.all()
    elif "vehicle_model" in request.path:
        qs = VehicleModel.objects.all()
    elif "engine_model" in request.path:
        qs = EngineModel.objects.all()
    elif "transmission_model" in request.path:
        qs = TransmissionModel.objects.all()
    elif "drive_axle_model" in request.path:
        qs = DriveAxle.objects.all()
    elif "steering_axle_model" in request.path:
        qs = SteeringAxle.objects.all()
    elif "failure_node" in request.path:
        qs = FailureNode.objects.all()
    elif "recovery_method" in request.path:
        qs = RecoveryMethod.objects.all()
    elif "view_maintenance" in request.path:
        qs = ViewMaintenance.objects.all()

    paginator = Paginator(qs, 5)

    try:
        current_page = paginator.page(int(page))
    except EmptyPage:
        current_page = paginator.page(int(page) - 1)

    context = {
        "title": "Справочники",
        "deskbook": current_page,
    }

    return render(request, "deskbook/deskbook.html", context=context)


@login_required
def remove_deskbook(request, slug, item_id):
    deskbook_delete_permission = [f'deskbook.{el}' for el in Permission.objects.filter(
        content_type__app_label="deskbook", codename__startswith="delete"
    ).values_list("codename", flat=True)]

    if not request.user.has_perms(deskbook_delete_permission):
        raise PermissionDenied
    
    if slug == "service_company":
        removable = get_object_or_404(ServiceCompany, id=item_id)
    elif slug == "vehicle_model":
        removable = get_object_or_404(VehicleModel, id=item_id)
    elif slug == "engine_model":
        removable = get_object_or_404(EngineModel, id=item_id)
    elif slug == "transmission_model":
        removable = get_object_or_404(TransmissionModel, id=item_id)
    elif slug == "drive_axle_model":
        removable = get_object_or_404(DriveAxle, id=item_id)
    elif slug == "steering_axle_model":
        removable = get_object_or_404(SteeringAxle, id=item_id)
    elif slug == "failure_node":
        removable = get_object_or_404(FailureNode, id=item_id)
    elif slug == "recovery_method":
        removable = get_object_or_404(RecoveryMethod, id=item_id)
    elif slug == "view_maintenance":
        removable = get_object_or_404(ViewMaintenance, id=item_id)

    removable.delete()

    try:
        return redirect(request.META["HTTP_REFERER"])
    except EmptyPage:
        return HttpResponseRedirect(reverse(f"deskbook:{slug}"))


@login_required
def edit_deskbook(request, slug, item_id):
    deskbook_change_permission = [f'deskbook.{el}' for el in Permission.objects.filter(
        content_type__app_label="deskbook", codename__startswith="change"
     ).values_list("codename", flat=True)]
    
    if not request.user.has_perms(deskbook_change_permission):
        raise PermissionDenied
    
    if slug == "service_company":
        item = get_object_or_404(ServiceCompany, id=item_id)
    elif slug == "vehicle_model":
        item = get_object_or_404(VehicleModel, id=item_id)
    elif slug == "engine_model":
        item = get_object_or_404(EngineModel, id=item_id)
    elif slug == "transmission_model":
        item = get_object_or_404(TransmissionModel, id=item_id)
    elif slug == "drive_axle_model":
        item = get_object_or_404(DriveAxle, id=item_id)
    elif slug == "steering_axle_model":
        item = get_object_or_404(SteeringAxle, id=item_id)
    elif slug == "failure_node":
        item = get_object_or_404(FailureNode, id=item_id)
    elif slug == "recovery_method":
        item = get_object_or_404(RecoveryMethod, id=item_id)
    elif slug == "view_maintenance":
        item = get_object_or_404(ViewMaintenance, id=item_id)

    if request.method == "GET":
        if slug == "service_company":
            form = EditServiceCompany(instance=item)
        elif slug == "vehicle_model":
            form = EditVehicleForm(instance=item)
        elif slug == "engine_model":
            form = EditEngineForm(instance=item)
        elif slug == "transmission_model":
            form = EditTransmissionForm(instance=item)
        elif slug == "drive_axle_model":
            form = EditDriveAxleForm(instance=item)
        elif slug == "steering_axle_model":
            form = EditSteeringAxleForm(instance=item)
        elif slug == "failure_node":
            form = EditFailureNodeForm(instance=item)
        elif slug == "recovery_method":
            form = EditRecoveryMethodForm(instance=item)
        elif slug == "view_maintenance":
            form = EditViewMaintenanceForm(instance=item)

    elif request.method == "POST":
        if slug == "service_company":
            form = EditServiceCompany(data=request.POST, instance=item)
        elif slug == "vehicle_model":
            form = EditVehicleForm(data=request.POST, instance=item)
        elif slug == "engine_model":
            form = EditEngineForm(data=request.POST, instance=item)
        elif slug == "transmission_model":
            form = EditTransmissionForm(data=request.POST, instance=item)
        elif slug == "drive_axle_model":
            form = EditDriveAxleForm(data=request.POST, instance=item)
        elif slug == "steering_axle_model":

deskbook/templates/includes/filtrationsDeskbook.html
<input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" {% if 'vehicle_model' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio1" 
    onclick="window.location.href='{% url "deskbook:vehicle_model" %}'; return false"
>Модель техники</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off" {% if 'engine_model' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio2"
    onclick="window.location.href='{% url "deskbook:engine_model" %}'; return false"
>Модель двигателя</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off" {% if 'transmission_model' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio3"
    onclick="window.location.href='{% url "deskbook:transmission_model" %}'; return false"
>Модель трансмиссии</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio4" autocomplete="off" {% if 'drive_axle_model' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio4"
    onclick="window.location.href='{% url "deskbook:drive_axle_model" %}'; return false"
>Модель ведущего моста</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio5" autocomplete="off" {% if 'steering_axle_model' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio5"
    onclick="window.location.href='{% url "deskbook:steering_axle_model" %}'; return false"
>Модель управляемого моста</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio6" autocomplete="off" {% if 'failure_node' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio6"
    onclick="window.location.href='{% url "deskbook:failure_node" %}'; return false"
>Узел отказа</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio7" autocomplete="off" {% if 'recovery_method' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio7"
    onclick="window.location.href='{% url "deskbook:recovery_method" %}'; return false"
>Способ востановления</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio8" autocomplete="off" {% if 'view_maintenance' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio8"
    onclick="window.location.href='{% url "deskbook:view_maintenance" %}'; return false"
>Вид ТО</label>

<input type="radio" class="btn-check" name="btnradio" id="btnradio8" autocomplete="off" {% if 'service_company' in request.path %}checked{% endif %}>
<label class="btn btn-outline-primary" for="btnradio8"
    onclick="window.location.href='{% url "deskbook:service_company" %}'; return false"
>Сервисная компания</label>

deskbook/templates/includes/modal_deskbook.html
{% load static %}
<!-- Для справочника  -->
<div class="modal fade deskbookModal" id="deskbookModal" tabindex="-1" aria-labelledby="deskbookModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Справка</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body fs-5" id="deskbook-content">
                <div>
                    <p>Название - {{item.name}}</p>
                </div> 
                <div>
                    <p>Описание:</p>
                    <p> {{item.description}}</p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>