api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from api.views import CarsViewSet, MaintenanceViewSet, ReclamationViewSet

app_name = "api"

router = routers.DefaultRouter()

router.register(r"cars", CarsViewSet)
router.register(r"maintenance", MaintenanceViewSet)
router.register(r"reclamation", ReclamationViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Silant API",
        default_version="v1.0.0",
        description="obtaining data from the tables Cars, Maintenance, Reclamation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

urlpatterns += router.urls

app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.settings import DEBUG

handler403 = 'main.views.tr_handler403'
handler404 = 'main.views.tr_handler404'
handler500 = 'main.views.tr_handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('maintenance/', include('maintenance.urls', namespace='maintenance')),
    path('reclamation/', include('reclamation.urls', namespace='reclamation')),
    path('deskbook/', include('deskbook.urls', namespace='deskbook')),
    path('user/', include('users.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

cars/urls.py
from django.urls import path

from cars import views


app_name = 'cars'

urlpatterns = [
    # Поиск машины для незарегистрированных пользователей
    path('search/', views.car_search, name='car_search'),
    # Отображение всех машин для зарегестрированных пользователей
    path('all/', views.cars, name='cars'),
    # Пути для фильтрации по справочникам
    path('vehicle_model/<int:vehicle_model_id>', views.cars, name='vehicle'),
    path('engine_model/<int:engine_model_id>', views.cars, name='engine'),
    path('transmission_model/<int:transmission_model_id>', views.cars, name='transmission'),
    path('drive_axle_model/<int:drive_axle_model_id>', views.cars, name='drive_axle'),
    path('steering_axle_model/<int:steering_axle_model_id>', views.cars, name='steering_axle'),
    # добавление, удаление, редактирвование машин
    path('add_car/', views.add_car, name='add_car'),
    path('edit_car/<int:pk>', views.edit_car, name='edit_car'),
    path('remove_car/<int:car_id>', views.remove_car, name='remove_car'),
    # ajax запрос машины
    path('car_ajax', views.car_ajax, name='car_ajax'),
]

deskbook/urls.py
from django.urls import path

from deskbook import views


app_name = 'deskbook'

urlpatterns = [

    path('service_company/', views.get_deskbook, name='service_company'),
    path('vehicle_model/', views.get_deskbook, name='vehicle_model'),
    path('engine_model/', views.get_deskbook, name='engine_model'),
    path('transmission_model/', views.get_deskbook, name='transmission_model'),
    path('drive_axle_model/', views.get_deskbook, name='drive_axle_model'),
    path('steering_axle_model/', views.get_deskbook, name='steering_axle_model'),
    path('failure_node/', views.get_deskbook, name='failure_node'),
    path('recovery_method/', views.get_deskbook, name='recovery_method'),
    path('view_maintenance/', views.get_deskbook, name='view_maintenance'),

    path('add_deskbook/<slug:slug>', views.add_deskbook, name='add_deskbook'),
    path('edit_deskbook/<slug:slug>/<int:item_id>', views.edit_deskbook, name='edit_deskbook'),
    path('remove_deskbook/<slug:slug>/<int:item_id>', views.remove_deskbook, name='remove_deskbook'),

    path('deskbook_ajax/', views.deskbook_ajax, name='deskbook_ajax'),
]

maintenance/urls.py
from django.urls import path

from maintenance import views


app_name = 'maintenance'

urlpatterns = [
    # Отображение всех ТО для зарегестрированных пользователей
    path('all/', views.maintenance, name='maintenance_all'),
    # ТО для конкретной машины
    path('<int:car_id>/', views.get_maintenances, name='car_maintenances'),
    # Фильтрация ТО конкретной машины
    path('<int:car_id>/view_maintenance/<int:view_maintenance_id>', views.get_maintenances, name='car_maintenances_view'),
    path('<int:car_id>/service_company/<int:service_company_id>', views.get_maintenances, name='car_maintenances_service'),
    # Пути для фильтрации по справочникам всех ТО
    path('view_maintenance/<int:view_maintenance_id>', views.maintenance, name='view_maintenance'),
    path('car/<int:car_id>', views.maintenance, name='car'),
    path('service_company/<int:service_company_id>', views.maintenance, name='service_company'),
    # добавление, удаление, редактирвование ТО
    path('add_maintenance/', views.add_maintenance, name='add_maintenance'),
    path('add_maintenance/<int:car_id>', views.add_maintenance, name='add_maintenance_car'),
    path('edit_maintenance/<int:view_maintenance_id>', views.edit_maintenance, name='edit_maintenance'),
    path('remove_maintenance/<int:view_maintenance_id>', views.remove_maintenance, name='remove_maintenance'),
]

cars/models.py
from django.db import models
from django.urls import reverse

from deskbook.models import ServiceCompany, DriveAxle, EngineModel, TransmissionModel, VehicleModel, SteeringAxle
from users.models import User


class Cars(models.Model):
    serial_number_vehicle = models.CharField(
        verbose_name="Зав. № машины",
        max_length=32,
        null=False,
        blank=False,
    )
    vehicle_model = models.ForeignKey(
        to=VehicleModel,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Модель техники",
    )

    engine_model = models.ForeignKey(
        to=EngineModel,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Модель двигателя",
    )
    serial_number_of_the_engine = models.CharField(
        verbose_name="Зав. № двигателя",
        max_length=32,
        null=False,
        blank=False,
    )

    transmission_model = models.ForeignKey(
        to=TransmissionModel,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Модель трансмиссии",
    )
    serial_number_of_the_transmission = models.CharField(
        verbose_name="Зав. № трансмиссии",
        max_length=32,
        null=False,
        blank=False,
    )

    drive_axle_model = models.ForeignKey(
        to=DriveAxle,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Модель ведущего моста",
    )
    drive_axle_serial_number = models.CharField(
        verbose_name="Зав. № ведущего моста",
        max_length=32,
        null=False,
        blank=False,
    )

    steering_axle_model = models.ForeignKey(
        to=SteeringAxle,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Модель управляемого моста",
    )
    serial_number_of_the_steered_axle = models.CharField(
        verbose_name="Зав. № управляемого моста",
        max_length=32,
        null=False,
        blank=False,
    )

    supply_contract = models.CharField(
        verbose_name="Договор поставки №, дата",
        max_length=128,
        unique=False,
        null=True,
        blank=True,
    )

    date_shipped_from_factory = models.DateField(verbose_name="Дата отгрузки с завода")

    consignee = models.CharField(
        verbose_name="Грузополучатель (конечный потребитель)",
        max_length=128,
        unique=False,
        null=False,
        blank=False,
    )

    delivery_address = models.CharField(
        verbose_name="Адрес поставки (эксплуатации)",
        max_length=256,
        unique=False,
        null=False,
        blank=False,
    )

    equipment = models.TextField(
        verbose_name="Комплектация (доп. опции)", unique=False, null=True, blank=True
    )

    client = models.ForeignKey(
        to=User,
        on_delete=models.SET_DEFAULT,
        verbose_name='Клиент',
        default=None
    )

    service_company = models.ForeignKey(
        to=ServiceCompany,
        on_delete=models.SET_DEFAULT,
        verbose_name="Сервисная компания",
        default=None
    )

    class Meta:
        db_table = "car"
        verbose_name = "Машину"
        verbose_name_plural = "Машины"
        # сортировка по дате отгрузки
        ordering = ('engine_model',)

    def __str__(self):
        return f"{self.serial_number_vehicle} - {self.vehicle_model}"
    
    def get_absolute_url(self):
        return reverse("cars:cars")
    

cars/templates/cars/add_car.html
{% extends "base.html" %}

{% load static %}
{% load cars_tags %}


{% block content %}
    <div class="d-flex justify-content-end p-1">
        <h5>Ваша учетная запись - <strong>{{request.user.username}}</strong></h5>
    </div>

    <div class="container">
        <div class="col-lg-10 auth-width">
            
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                            <h2 class="text-center mb-4">{% if 'edit_car' in request.path %} Изменить данные машины {{car}}{% else %} Добавить машину{% endif %}</h2>
                            <form action="{% if 'edit_car' in request.path %}{% url "cars:edit_car" car.id %}{% else %} {% url "cars:add_car" %} {% endif %}" method="post">
                                                              
                                {% csrf_token %}
                                {% tag_list_deskbook as list_deskbook %}
                                {% for field in form  %}
                                    <div class="d-flex flex-column mb-3">
                                        {% if field.errors%}
                                            {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                {{error}}
                                            </div>
                                            {% endfor %}
                                        {% endif %}
                                        
                                        <div class="auth-width">
                                            <label for="{{field.id_for_label}}" class="form-label" >{{ field.label }}</label>
                                            <div class="d-flex flex-row justify-content-end">
                                                {{ field }}
                                                {% if field.name in list_deskbook %}
                                                    {% if user.user_role == 'MG' or user.user_role == 'AD' %}
                                                        <a href="{% url "deskbook:add_deskbook" field.name %}" class="m-2">
                                                            <img class="mx-1" src="{% static "source/icons/plus-lg.svg" %}" alt="Plus" width="16" height="16">
                                                        </a>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        </div> 
                                    </div>
                                {% endfor %}                                
                                
                                <button type="submit" class="btn btn-primary float-end">Сохранить</button> 
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

cars/templates/cars/car_search.html
{% extends "base.html" %}

{% load static %}

    {% block content %}

        {% include "includes/search.html" %}

        {% if request.GET.q %}
            <div class='mySearch d-flex justify-content-center'>
                <h3>Результат поиска по запросу заводского номера: {{request.GET.q}} </h3>
            </div>
            {% if not car_search %}<h4 class="d-flex justify-content-center">{{ content }}</h4>{% endif %}
        {% endif %}

        {% if car_search %}
            <div class='table-responsive-xxl'>
            <table class="table table-striped">
                <thead class='myTHead'>
                <tr>
                    <th scope="col">Зав. № машины</th>
                    <th scope="col">Модель техники</th>
                    <th scope="col">Модель двигателя</th>
                    <th scope="col">Зав. № двигателя</th>
                    <th scope="col">Модель трансмиссии</th>
                    <th scope="col">Зав. № трансмиссии</th>
                    <th scope="col">Модель ведущего моста</th>
                    <th scope="col">Зав. № ведущего моста</th>
                    <th scope="col">Модель управляемого моста</th>
                    <th scope="col">Зав. № управляемого моста</th>
                </tr>
                </thead>
                <tbody>
                {% for car in car_search %}
                    <tr>
                        <td>{{ car.serial_number_vehicle }}</td>
                        <td>{{ car.vehicle_model }}</td>
                        <td>{{ car.engine_model }}</td>
                        <td>{{ car.serial_number_of_the_engine }}</td>
                        <td>{{ car.transmission_model }}</td>
                        <td>{{ car.serial_number_of_the_transmission }}</td>
                        <td>{{ car.drive_axle_model }}</td>
                        <td>{{ car.drive_axle_serial_number }}</td>
                        <td>{{ car.steering_axle_model }}</td>
                        <td>{{ car.serial_number_of_the_steered_axle }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            </div>
        {% endif %}

    {% endblock %}


    

cars/templates/cars/cars.html
{% extends "base.html" %}

{% load static %}
{% load cars_tags %}

{% block content %}
    {% include "includes/user_info.html" %}
    <div class="d-flex justify-content-center p-4">
        <h4 class="text-center">Информация о комплектации и технических характеристиках Вашей техники </h4>
    </div>

    {% include "includes/radiobuttons.html" %}

    <div class="filtrationButtons">
        {% include "includes/CarFiltrationsButtons.html" %}
    </div>

    <button class="btn btn-primary filtrationButtonsCollaps ms-auto btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
        <img class="mx-1" src="{% static "source/icons/list.svg" %}" alt="Burger" width="24" height="24">
    </button>

    <div class="collapse collapse-horizontal" id="collapseWidthExample">
        <div class="filtrationButtonsCollaps">
            {% include "includes/CarFiltrationsButtons.html" %}
        </div>
    </div>

    <div class='table-responsive-xxl'>
        <table class="table table-striped">
        <thead class='myTHead'>
        <tr>
            <th scope="col" class="p-1">Зав. № машины</th>
            <th scope="col" class="p-1 {% if 'vehicle_model' in request.path %} colorRed {% endif %}">Модель техники</th>
            <th scope="col" class="p-1 {% if 'engine_model' in request.path %} colorRed {% endif %}">Модель двигателя</th>
            <th scope="col" class="p-1">Зав. № двигателя</th>
            <th scope="col" class="p-1 {% if 'transmission_model' in request.path %} colorRed {% endif %}">Модель трансмиссии</th>
            <th scope="col" class="p-1">Зав. № трансмиссии</th>
            <th scope="col" class="p-1 {% if 'drive_axle_model' in request.path %} colorRed {% endif %}">Модель ведущего моста</th>
            <th scope="col" class="p-1">Зав. № ведущего моста</th>
            <th scope="col" class="p-1 {% if 'steering_axle_model' in request.path %} colorRed {% endif %}">Модель управляемого моста</th>
            <th scope="col" class="p-1">Зав. № управляемого моста</th>
            <th scope="col" class="p-1">Договор поставки №, дата</th>
            <th scope="col" class="p-1">Дата отгрузки с завода</th>
            <th scope="col" class="p-1">Грузополучатель (конечный потребитель)</th>
            <th scope="col" class="p-1">Адрес поставки (эксплуатации)</th>
            <th scope="col" class="p-1">Комплектация (доп. опции)</th>
            <th scope="col" class="p-1">Клиент</th>
            <th scope="col" class="p-1">Сервисная компания</th>
            <th scope="col" class="p-1"></th>
        </tr>
        </thead>
        <tbody>
        {% for car in cars %}
        
            <tr 
            {% comment %} onclick="window.location.href='{% url "cars:car" car.id %}'; return false" {% endcomment %}
            >
                
                <td class="align-middle p-2">
                    <div class='d-inline-flex justify-content-between align-items-center' >
                        <a class="align-middle fs-6" href="{% url "maintenance:car_maintenances" car.id %}">{{ car.serial_number_vehicle }}</a>

                        <a href="{% url "cars:car_ajax" %}" class="modalCarLink ms-2" aria-expanded="false" data-car-id="{{ car.id }}" >
                            <img class="mx-1" src="{% static "source/icons/box-arrow-up-right.svg" %}" alt="box-arrow" width="16" height="16">
                        </a>
                    </div>
                </td>
                <td class="align-middle p-2"> 
                    <div class='d-inline-flex justify-content-between align-items-center' >
                        {{ car.vehicle_model }}
                        <a href="{% url "deskbook:deskbook_ajax" %}" class="modalLink" aria-expanded="false" data-deskbook-name="vehicle_model" data-deskbook-id="{{ car.vehicle_model.id}}">
                            <img class="mx-1" src="{% static "source/icons/question.svg" %}" alt="Trash" width="16" height="16">
                        </a>
                    </div>

                </td>
                <td class="align-middle p-2" >
                    <div class='d-inline-flex justify-content-between align-items-center' >
                        {{ car.engine_model }}
                        <a href="{% url "deskbook:deskbook_ajax" %}" class="modalLink" aria-expanded="false" data-deskbook-name="engine_model" data-deskbook-id="{{ car.engine_model.id}}">
                            <img class="mx-1" src="{% static "source/icons/question.svg" %}" alt="Trash" width="16" height="16">
                        </a>
                    </div>
                </td>
                <td class="align-middle p-2">{{ car.serial_number_of_the_engine }}</td>
                <td class="align-middle p-2">
                    <div class='d-inline-flex justify-content-between align-items-center' >
                        {{ car.transmission_model }}
                        <a href="{% url "deskbook:deskbook_ajax" %}" class="modalLink" data-deskbook-name="transmission_model" data-deskbook-id="{{ car.transmission_model.id}}">
                            <img class="mx-1" src="{% static "source/icons/question.svg" %}" alt="Trash" width="16" height="16">
                        </a>
                    </div>
                </td>
                <td class="align-middle p-2">{{ car.serial_number_of_the_transmission }}</td>
                <td class="align-middle p-2">
                    <div class='d-inline-flex justify-content-between align-items-center' >
                        {{ car.drive_axle_model }}
                        <a href="{% url "deskbook:deskbook_ajax" %}" class="modalLink" data-deskbook-name="drive_axle_model" data-deskbook-id="{{ car.drive_axle_model.id}}">
                            <img class="mx-1" src="{% static "source/icons/question.svg" %}" alt="Trash" width="16" height="16">
                        </a>
                    </div>
                </td>
                <td class="align-middle p-2">{{ car.drive_axle_serial_number }}</td>
                <td class="align-middle p-2">
                    <div class='d-inline-flex justify-content-between align-items-center' >
                        {{ car.steering_axle_model }}
                        <a href="{% url "deskbook:deskbook_ajax" %}" class="modalLink" data-deskbook-name="steering_axle_model" data-deskbook-id="{{ car.steering_axle_model.id}}">
                            <img class="mx-1" src="{% static "source/icons/question.svg" %}" alt="Trash" width="16" height="16">
                        </a>
                    </div>
                </td>
                <td class="align-middle p-2">{{ car.serial_number_of_the_steered_axle }}</td>
                <td class="align-middle p-2">{% if not car.supply_contract %} Не указан {% else %}{{ car.supply_contract }}{% endif %}</td>
                <td class="align-middle p-2">{{ car.date_shipped_from_factory }}</td>
                <td class="align-middle p-2">{{ car.consignee }}</td>
                <td class="align-middle p-2">{{ car.delivery_address }}</td>
                <td class="align-middle p-2">{{ car.equipment|truncatechars:40 }}</td>
                <td class="align-middle p-2">{{ car.client }}</td>
                <td class="align-middle p-2">
                    <div class='d-inline-flex justify-content-between align-items-center' >
                        {{ car.service_company }}
                        <a href="{% url "deskbook:deskbook_ajax" %}" class="modalLink" data-deskbook-name="service_company" data-deskbook-id="{{ car.service_company.id}}">
                            <img class="mx-1" src="{% static "source/icons/question.svg" %}" alt="Trash" width="16" height="16">
                        </a>
                    </div>
                </td>
                <td class="p-1 align-middle">
                    <div class="d-inline-flex justify-content-between">
                        {% if perms.cars.delete_cars %}
                            <a href="#" class="remove-from-cart m-2" data-bs-toggle="modal" data-bs-target="#exampleModal_{{car.id}}">
                                <img class="mx-1" src="{% static "source/icons/trash3-fill.svg" %}" alt="Trash" width="16" height="16">
                            </a>
                        {% endif %}
                        {% if perms.cars.change_cars %}
                            <a href="{% url "cars:edit_car" pk=car.id %}" class="remove-from-cart m-2">
                                <img class="mx-1" src="{% static "source/icons/tools.svg" %}" alt="Tools" width="16" height="16">
                            </a>
                        {% endif %}
                    </div>
                    
                      <!-- Modal -->
                    <div class="modal fade" id="exampleModal_{{car.id}}" tabindex="-1" aria-labelledby="exampleModalLabel_{{car.id}}" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body fs-5">
                                Вы действительно хотите удалить машину {{car}}?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                                <button type="button" class="btn btn-primary" 
                                    onclick="window.location.href='{% url "cars:remove_car" car.id %}'; return false">Удалить</button>
                            </div>
                        </div>
                        </div>
                    </div>

                </td>
                
            </tr>
        {% endfor %}

        </tbody>
        </table>
    </div>
    
    {% if not cars %} <div class="d-flex justify-content-center"><h3>Нет данных о машинах</h3></div> {% endif %}
<!-- Пагинация -->
{% if cars %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not cars.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if cars.has_previous %}?{% change_params page=cars.previous_page_number %}
                {% else %}
                    #
                {% endif %}">Назад</a>
            </li>

            {% for page in cars.paginator.page_range %}
                {% if page >= cars.number|add:-2 and page <= cars.number|add:2 %}
                    <li class="page-item {% if cars.number == page %} active {% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item {% if not cars.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if cars.has_next %}?{% change_params page=cars.next_page_number %}
                {% else %}
                    #
                {% endif %}">Вперед</a>
            </li>
        </ul>
    </nav>
{% endif %}
   
{% endblock %}

cars/templates/cars/index.html
{% extends "cars/base.html" %}
{% load static %}

{% block section %}
  <div class='myHead'>
    <h3>Проверьте комплектацию и технические характеристики техники Силант</h3>
  </div>

  <nav class="navbar bg-body-tertiary colorGray">
    <div class="container-fluid">
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Заводской номер" aria-label="Search">
        <button class="btn btn-outline-primary me-2" type="submit">Поиск</button>
      </form>
    </div>
  </nav>

  <div class='mySearch'>
    <h3>Результат поиска:</h3>
  </div>

  <div class='myHead'>
    <h4>{{ content }}</h4>
  </div>

  <table class="table table-striped">
    <thead class='myTHead'>
      <tr>
        <th scope="col">Зав. № машины</th>
        <th scope="col">Модель техники</th>
        <th scope="col">Модель двигателя</th>
        <th scope="col">Зав. № двигателя</th>
        <th scope="col">Модель трансмиссии</th>
        <th scope="col">Зав. № трансмиссии</th>
        <th scope="col">Модель ведущего моста</th>
        <th scope="col">Зав. № ведущего моста</th>
        <th scope="col">Модель управляемого моста</th>
        <th scope="col">Зав. № управляемого моста</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Mark</td>
        <td>Otto</td>
        <td>@mdo</td>
        <td>@mdo</td>
        <td>@mdo</td>
        <td>@mdo</td>
        <td>@mdo</td>
        <td>@mdo</td>
        <td>@mdo</td>
        <td>@mdo</td>
      </tr>

    </tbody>
  </table>

{% endblock section %}

        
    