api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from api.views import CarsViewSet, MaintenanceViewSet, ReclamationViewSet

app_name = "api"

router = routers.DefaultRouter()

router.register(r"cars", CarsViewSet)
router.register(r"maintenance", MaintenanceViewSet)
router.register(r"reclamation", ReclamationViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Silant API",
        default_version="v1.0.0",
        description="obtaining data from the tables Cars, Maintenance, Reclamation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

urlpatterns += router.urls

app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.settings import DEBUG

handler403 = 'main.views.tr_handler403'
handler404 = 'main.views.tr_handler404'
handler500 = 'main.views.tr_handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('maintenance/', include('maintenance.urls', namespace='maintenance')),
    path('reclamation/', include('reclamation.urls', namespace='reclamation')),
    path('deskbook/', include('deskbook.urls', namespace='deskbook')),
    path('user/', include('users.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

deskbook/urls.py
from django.urls import path

from deskbook import views


app_name = 'deskbook'

urlpatterns = [

    path('service_company/', views.get_deskbook, name='service_company'),
    path('vehicle_model/', views.get_deskbook, name='vehicle_model'),
    path('engine_model/', views.get_deskbook, name='engine_model'),
    path('transmission_model/', views.get_deskbook, name='transmission_model'),
    path('drive_axle_model/', views.get_deskbook, name='drive_axle_model'),
    path('steering_axle_model/', views.get_deskbook, name='steering_axle_model'),
    path('failure_node/', views.get_deskbook, name='failure_node'),
    path('recovery_method/', views.get_deskbook, name='recovery_method'),
    path('view_maintenance/', views.get_deskbook, name='view_maintenance'),

    path('add_deskbook/<slug:slug>', views.add_deskbook, name='add_deskbook'),
    path('edit_deskbook/<slug:slug>/<int:item_id>', views.edit_deskbook, name='edit_deskbook'),
    path('remove_deskbook/<slug:slug>/<int:item_id>', views.remove_deskbook, name='remove_deskbook'),

    path('deskbook_ajax/', views.deskbook_ajax, name='deskbook_ajax'),
]

maintenance/urls.py
from django.urls import path

from maintenance import views


app_name = 'maintenance'

urlpatterns = [
    # Отображение всех ТО для зарегестрированных пользователей
    path('all/', views.maintenance, name='maintenance_all'),
    # ТО для конкретной машины
    path('<int:car_id>/', views.get_maintenances, name='car_maintenances'),
    # Фильтрация ТО конкретной машины
    path('<int:car_id>/view_maintenance/<int:view_maintenance_id>', views.get_maintenances, name='car_maintenances_view'),
    path('<int:car_id>/service_company/<int:service_company_id>', views.get_maintenances, name='car_maintenances_service'),
    # Пути для фильтрации по справочникам всех ТО
    path('view_maintenance/<int:view_maintenance_id>', views.maintenance, name='view_maintenance'),
    path('car/<int:car_id>', views.maintenance, name='car'),
    path('service_company/<int:service_company_id>', views.maintenance, name='service_company'),
    # добавление, удаление, редактирвование ТО
    path('add_maintenance/', views.add_maintenance, name='add_maintenance'),
    path('add_maintenance/<int:car_id>', views.add_maintenance, name='add_maintenance_car'),
    path('edit_maintenance/<int:view_maintenance_id>', views.edit_maintenance, name='edit_maintenance'),
    path('remove_maintenance/<int:view_maintenance_id>', views.remove_maintenance, name='remove_maintenance'),
]

maintenance/models.py
from django.db import models
from django.urls import reverse

from deskbook.models import ViewMaintenance, ServiceCompany
from cars.models import Cars


# Create your models here.
class Maintenance(models.Model):
    view_maintenance = models.ForeignKey(
        to=ViewMaintenance, on_delete=models.SET_DEFAULT, default=None, verbose_name="Вид ТО"
    )
    Date_maintenance = models.DateField(verbose_name="Дата проведения ТО")
    operating_hours = models.IntegerField(verbose_name="Наработка, м/час")
    work_order_number = models.CharField(
        verbose_name="№ заказ-наряда",
        max_length=128,
        null=False,
        blank=False,
    )
    work_order_date = models.DateField(verbose_name="Дата заказ-наряда")
    # organization = models.CharField(verbose_name='Организация, проводившая ТО', max_length=128, unique=False, null=False, blank=False)
    car = models.ForeignKey(
        to=Cars,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Машина",
    )
    service_company = models.ForeignKey(
        to=ServiceCompany,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Сервисная компания",
    )

    class Meta:
        db_table = "maintenance"
        verbose_name = "ТО"
        verbose_name_plural = "ТО"
        ordering = ("car",)

    def __str__(self):
        return f"{self.car} - {self.view_maintenance}"
    
    def get_absolute_url(self):
        return reverse("maintenance:maintenance_all")
    

maintenance/forms.py
from django import forms
from django.db.models import Q

from cars.models import Cars
from deskbook.models import ViewMaintenance, ServiceCompany
from maintenance.models import Maintenance


class AddMaintenanceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        if "car_id" in kwargs:
            car_id = kwargs.pop("car_id")
            qs_car = Cars.objects.filter(id=car_id)
            # список ТО машины car_id
            maintenance_list = (
                Maintenance.objects.all()
                .filter(car__id=car_id)
                .values_list("view_maintenance", flat=True)
            )
            # queryset без проведенных ТО
            qs_view_maintenance = ViewMaintenance.objects.exclude(
                Q(pk__in=maintenance_list)
            )
        else:
            qs_car = Cars.objects.all()
            qs_view_maintenance = ViewMaintenance.objects.all()
        super(AddMaintenanceForm, self).__init__(*args, **kwargs)
        self.fields["car"].queryset = qs_car
        self.fields["view_maintenance"].queryset = qs_view_maintenance

    class Meta:
        model = Maintenance
        fields = "__all__"

    view_maintenance = forms.ModelChoiceField(
        queryset=None,
        label="Вид технического обслуживания: ",
        empty_label="Выберите ТО",
        widget=forms.Select(attrs={"class": "form-select auth-width"}),
    )

    Date_maintenance = forms.DateField(
        label="Дата проведения технического обслуживания: ",
        widget=forms.DateInput(
            attrs={"placeholder": "Укажите дату", "class": "form-control auth-width"}
        ),
    )

    operating_hours = forms.IntegerField(
        label="Наработка, моточас: ",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Введите число",
                "class": "form-control auth-width",
            }
        ),
    )

    work_order_number = forms.CharField(
        label="№ заказ-наряда: ",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Введите номер",
                "class": "form-control auth-width",
            }
        ),
    )

    work_order_date = forms.DateField(
        label="Дата выдачи заказ-наряда: ",
        widget=forms.DateInput(
            attrs={"placeholder": "Укажите дату", "class": "form-control auth-width"}
        ),
    )

    car = forms.ModelChoiceField(
        queryset=None,
        label="Машина: ",
        empty_label="Выберите машину",
        widget=forms.Select(attrs={"class": "form-select auth-width"}),
    )

    service_company = forms.ModelChoiceField(
        queryset=ServiceCompany.objects.all(),
        label="Сервисная компания: ",
        empty_label="Выберите компанию",
        widget=forms.Select(attrs={"class": "form-select auth-width"}),
    )

maintenance/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.paginator import EmptyPage, Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from cars.models import Cars
from maintenance.forms import AddMaintenanceForm
from maintenance.models import Maintenance


@permission_required('maintenance.view_maintenance', raise_exception=True)
def maintenance(
    request, view_maintenance_id=False, car_id=False, service_company_id=False
):    
    page = request.GET.get("page", 1)
    ordering = request.GET.get("order_by", None)
    user_role = request.user.user_role

    if user_role == 'CL':
        user_cars = Cars.objects.filter(client=request.user.id)
        user_cars_list_id = user_cars.values_list('id', flat=True)
        maintenance_limited = Maintenance.objects.filter(car__in=user_cars_list_id)
    elif user_role == 'SE':
        user_cars = Cars.objects.filter(service_company=request.user.service_company_id)
        maintenance_limited = Maintenance.objects.filter(service_company=request.user.service_company_id)
    elif user_role == 'MG' or user_role == 'AD':
        user_cars = Cars.objects.all()
        maintenance_limited = Maintenance.objects.all()

    view_maintenance_for_filtration = maintenance_limited.values_list('view_maintenance', flat=True)
    service_company_for_filtration = maintenance_limited.values_list('car', flat=True)

    if view_maintenance_id:
        user_maintenance = maintenance_limited.filter(
            view_maintenance=view_maintenance_id
        )
    elif car_id:
        user_maintenance = maintenance_limited.filter(
            car=car_id
        )
    elif service_company_id:
        user_maintenance = maintenance_limited.filter(
            service_company__id=service_company_id
        )
    else:
        user_maintenance = maintenance_limited

    if ordering and ordering != "default":
        user_maintenance = user_maintenance.order_by(ordering)

    paginator = Paginator(user_maintenance, 5)
    current_page = paginator.page(int(page))

    context = {
        "title": "ТО", 
        "maintenance": current_page,
        'vm_for_filter': view_maintenance_for_filtration,
        'serial_number': user_cars,
        'sc_for_filter': service_company_for_filtration,
    }
    
    return render(request, "maintenance/maintenance_all.html", context)


@permission_required('maintenance.view_maintenance', raise_exception=True)
def get_maintenances(request, car_id, view_maintenance_id=False, service_company_id=False):

    page = request.GET.get("page", 1)
    ordering = request.GET.get("order_by", None)

    if view_maintenance_id:
        maintenances_list = Maintenance.objects.filter(car__id=car_id).filter(
            view_maintenance=view_maintenance_id
        )
    elif service_company_id:
        maintenances_list = Maintenance.objects.filter(car__id=car_id).filter(
            service_company=service_company_id
        )
    else:
        maintenances_list = Maintenance.objects.filter(car__id=car_id)

    view_maintenance_for_watch = maintenances_list.values_list('view_maintenance', flat=True)
    service_company_for_watch = maintenances_list.values_list('service_company', flat=True)

    if ordering and ordering != "default":
        maintenances_list = maintenances_list.order_by(ordering)

    car_item = Cars.objects.get(id=car_id)

    paginator = Paginator(maintenances_list, 4)

    try:
        current_page = paginator.page(int(page))
    except EmptyPage:
        current_page = paginator.page(int(page) - 1)
    
    context = {
        "title": "ТО", 
        "maintenances": current_page, 
        'car': car_item,
        'sc_for_watch': service_company_for_watch,
        'wm_for_watch': view_maintenance_for_watch,
    }

    return render(request, 'maintenance/maintenances.html', context)


@permission_required('maintenance.add_maintenance', raise_exception=True)
def add_maintenance(request, car_id=False):
    if request.method == "POST":
        form = AddMaintenanceForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, f"{request.user.username}, Вы успешно добавили ТО!"
            )
            if not car_id:
                return HttpResponseRedirect(reverse("maintenance:maintenance_all"))
            else:
                return HttpResponseRedirect(reverse("maintenance:car_maintenances", args=(car_id,)))
        else:
            messages.warning(
                request, f"{request.user.username}, Вы неверно ввели данные!"
            )
    elif request.method == "GET" and car_id:
        car = get_object_or_404(Cars, pk=car_id)
        car_list = Cars.objects.filter(id=car_id).values('id')[0]['id']
        form = AddMaintenanceForm(initial={'car': car_list}, car_id=car_id)
    else:
        form = AddMaintenanceForm()
        car = car_id

    context = {
        'title': 'ТО',
        'form': form,
        'car': car,
    }
    return render(request, 'maintenance/add_maintenance.html', context)


@permission_required('maintenance.change_maintenance', raise_exception=True)
def edit_maintenance(request, view_maintenance_id):
    item = get_object_or_404(Maintenance, id=view_maintenance_id)
    car_id = item.car.id
    if request.method == "POST":
        form = AddMaintenanceForm(data=request.POST, instance=item)
        if form.is_valid():
            form.save()
            messages.success(
                request, f"{request.user.username}, Вы успешно изменили ТО!"
            )
            return HttpResponseRedirect(reverse("maintenance:car_maintenances", args=(car_id,)))
        else:
            messages.warning(
                request, f"{request.user.username}, Вы неверно ввели данные!"
            )
    else:
        form = AddMaintenanceForm(instance=item)

    context = {
        'title': 'ТО',
        'form': form,
        'item': item,
    }
    return render(request, 'maintenance/add_maintenance.html', context)


@permission_required('maintenance.delete_maintenance', raise_exception=True)
def remove_maintenance(request, view_maintenance_id):
    removable = Maintenance.objects.get(id=view_maintenance_id)
    removable.delete()
    messages.success(
        request, f"{request.user.username}, Вы успешно удалили ТО {removable}!"
    )
    try:
        return redirect(request.META["HTTP_REFERER"])
    except EmptyPage:
        return HttpResponseRedirect(reverse("maintenance:maintenance_all"))

maintenance/templates/maintenance/add_maintenance.html
{% extends "base.html" %}

{% load static %}
{% load maintenance_tags %}

{% block content %}
    <div class="d-flex justify-content-end p-1">
        <h5>Ваша учетная запись - <strong>{{request.user.username}}</strong></h5>
    </div>

    {% if car %}
        <div class="d-flex justify-content-around p-2">
            <h4 class="name_car">Модель техники: {{car.vehicle_model}}</h4>
            <h4 class="serial_number_vehicle">Заводской номер: {{car.serial_number_vehicle}} </h4>
        </div>
    {% endif %}

    <div class="container">
        <div class="col-lg-10 auth-width">
            
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                            {% if 'add_maintenance' in request.path%}
                                <h2 class="text-center mb-4">Добавить техническое обслуживание</h2>
                            {% else %}
                                <h2 class="text-center mb-4">Редактировать техническое обслуживание</h2>
                            {% endif %}
                            
                            <form action="
                                {% if 'add_maintenance' in request.path and request.resolver_match.kwargs %}
                                    {% url "maintenance:add_maintenance_car" car.id %}
                                {% elif 'edit_maintenance' in request.path %}
                                    {% url "maintenance:edit_maintenance" item.id %}
                                {% else %}
                                    {% url "maintenance:add_maintenance" %}
                                {% endif %}" 
                            method="post">
                                {% csrf_token %}
                                {% tag_list_deskbook as list_deskbook %}
                                {% for field in form  %}
                                    <div class="d-flex flex-column mb-3">

                                        {% if field.errors%}
                                            {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                {{error}}
                                            </div>
                                            {% endfor %}
                                        {% endif %}

                                        <div class="auth-width">
                                            <label for="{{field.id_for_label}}" class="form-label" >{{ field.label }}</label>
                                            <div class="d-flex flex-row justify-content-end">
                                                {{ field }}
                                                {% if field.name in list_deskbook %}
                                                    {% if user.user_role == 'MG' or user.user_role == 'AD' %}
                                                        <a href="{% url "deskbook:add_deskbook" field.name %}" class="m-2">
                                                            <img class="mx-1" src="{% static "source/icons/plus-lg.svg" %}" alt="Plus" width="16" height="16">
                                                        </a>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}                                

                                <button type="submit" class="btn btn-primary float-end">Сохранить</button> 
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

maintenance/templates/maintenance/maintenance.html
{% extends "base.html" %}

{% load static %}

{% load maintenance_tags %}

{% block content %}

    <div class="d-flex justify-content-end p-1">
        <h5>Ваша учетная запись - <strong>{{request.user.username}}</strong></h5>
    </div>

    <div class="d-flex justify-content-center p-4">
        <h4>Информация о проведенных ТО Вашей техники </h4>
    </div>

    {% include "includes/radiobuttons.html" %}
    
    <div class="d-flex pt-5">
            <!-- Форма сортировки -->
        <div class="dropdown mb-2 me-2">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Сортировка таблицы
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item fontSizeBtn" href="?order_by=default">По умолчанию</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item fontSizeBtn" href="?order_by=Date_maintenance">По возрастанию даты проведения ТО</a></li>
                <li><a class="dropdown-item fontSizeBtn" href="?order_by=-Date_maintenance">По убыванию даты проведения ТО</a></li>    
            </ul>
        </div>
            <!-- Фильтрация по виду ТО -->
        <div class="dropdown mb-2 me-2">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Вид ТО
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item fontSizeBtn" href="{% url "maintenance:maintenance" %}">Все виды</a></li>
                <li><hr class="dropdown-divider"></li>
                {% tag_view_maintenance as view_maintenance %}
                {% for view in view_maintenance %}
                    <li>
                        <a class="dropdown-item fontSizeBtn" href="{% url "maintenance:view_maintenance" view.id %}">
                            {{ view.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
            <!-- Фильтрация по машине -->
        <div class="dropdown mb-2 me-2">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Машина
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item fontSizeBtn" href="{% url "maintenance:maintenance" %}">Все машины</a></li>
                <li><hr class="dropdown-divider"></li>
                {% tag_vehicle_models as vehicle_models %}
                {% for car in vehicle_models %}
                    <li>
                        <a class="dropdown-item fontSizeBtn" href="{% url "maintenance:car" car.id %}">
                            {{ car.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

            <!-- Фильтрация по сервисная компания -->
        <div class="dropdown mb-2 me-2">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Сервисная компания
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item fontSizeBtn" href="{% url "maintenance:maintenance" %}">Все компании</a></li>
                <li><hr class="dropdown-divider"></li>
                {% tag_service_company as service_company %}
                {% for company in service_company %}
                    <li>
                        <a class="dropdown-item fontSizeBtn" href="{% url "maintenance:service_company" company.id %}">
                            {{ company.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>

    <table class="table table-striped">
        <thead class='myTHead'>
        <tr>
            <th scope="col">Машина</th>
            <th scope="col">Вид ТО</th>
            <th scope="col">Дата проведения ТО</th>
            <th scope="col">Наработка, м/час</th>
            <th scope="col">№ заказ-наряда</th>
            <th scope="col">Дата заказ-наряда</th>
            <th scope="col">Сервисная компания</th>
        </tr>
        </thead>

        <tbody>
        {% for item in maintenance %}
        
            <tr 
                onclick="window.location.href='{% url "maintenance:this_maintenance" item.id %}'; return false"
            >
                
                <td>{{ item.car.vehicle_model }}</td>
                <td>{{ item.view_maintenance }}</td>
                <td>{{ item.Date_maintenance }}</td>
                <td>{{ item.operating_hours }}</td>
                <td>{{ item.work_order_number }}</td>
                <td>{{ item.work_order_date }}</td>
                <td>{{ item.service_company }}</td>
                
            </tr>
        
        {% endfor %}

        </tbody>
    </table>

    <!-- Пагинация -->
{% if maintenance %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not maintenance.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if maintenance.has_previous %}?{% change_params page=maintenance.previous_page_number %}
                {% else %}
                    #
                {% endif %}">Назад</a>
            </li>

            {% for page in maintenance.paginator.page_range %}
                {% if page >= maintenance.number|add:-2 and page <= maintenance.number|add:2 %}
                    <li class="page-item {% if maintenance.number == page %} active {% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item {% if not maintenance.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if maintenance.has_next %}?{% change_params page=maintenance.next_page_number %}
                {% else %}
                    #
                {% endif %}">Вперед</a>
            </li>
        </ul>
    </nav>
{% endif %}

{% endblock %}