api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from api.views import CarsViewSet, MaintenanceViewSet, ReclamationViewSet

app_name = "api"

router = routers.DefaultRouter()

router.register(r"cars", CarsViewSet)
router.register(r"maintenance", MaintenanceViewSet)
router.register(r"reclamation", ReclamationViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Silant API",
        default_version="v1.0.0",
        description="obtaining data from the tables Cars, Maintenance, Reclamation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

urlpatterns += router.urls

app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.settings import DEBUG

handler403 = 'main.views.tr_handler403'
handler404 = 'main.views.tr_handler404'
handler500 = 'main.views.tr_handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('maintenance/', include('maintenance.urls', namespace='maintenance')),
    path('reclamation/', include('reclamation.urls', namespace='reclamation')),
    path('deskbook/', include('deskbook.urls', namespace='deskbook')),
    path('user/', include('users.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

reclamation/urls.py
from django.urls import path

from reclamation import views


app_name = 'reclamation'

urlpatterns = [
    # Отображение всех рекламаций
    path('all/', views.reclamation, name='reclamation_all'),
    # Рекламации конкретной машины
    path('<int:car_id>', views.get_reclamation, name='car_reclamations'),
    # Фильтрация рекламаций конкретной машины
    path('<int:car_id>/failure_node/<int:failure_node_id>', views.get_reclamation, name='car_reclamations_failure_node'),
    path('<int:car_id>/recovery_method/<int:recovery_method_id>', views.get_reclamation, name='car_reclamations_recovery_method'),
    path('<int:car_id>/service_company/<int:service_company_id>', views.get_reclamation, name='car_reclamations_service_company'),
    # Фильтрация всех рекламаций
    path('failure_node/<int:failure_node_id>', views.reclamation, name='failure_node'),
    path('recovery_method/<int:recovery_method_id>', views.reclamation, name='recovery_method'),
    path('service_company/<int:service_company_id>', views.reclamation, name='service_company'),
    # Добавление, удаление, редактирование рекламации
    path('add_reclamation/', views.add_reclamation, name='add_reclamation'),
    path('add_reclamation/<int:car_id>', views.add_reclamation, name='add_reclamation_car'),
    path('edit_reclamation/<int:reclamation_id>', views.edit_reclamation, name='edit_reclamation'),
    path('remove_reclamation/<int:reclamation_id>', views.remove_reclamation, name='remove_reclamation'),
]

reclamation/models.py
from django.db import models
from django.urls import reverse

from cars.models import Cars
from deskbook.models import FailureNode, RecoveryMethod, ServiceCompany

# Create your models here.
class Reclamation(models.Model):
    date_of_refusal = models.DateField(verbose_name="Дата отказа")
    operating_hours = models.IntegerField(verbose_name="Наработка, м/час")
    failure_node = models.ForeignKey(
        to=FailureNode, on_delete=models.SET_DEFAULT, default=None, verbose_name="Узел отказа"
    )
    description_of_failure = models.TextField(
        verbose_name="Описание отказа", unique=False, null=True, blank=True
    )
    recovery_method = models.ForeignKey(
        to=RecoveryMethod,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Способ восстановления",
    )
    parts_used = models.TextField(
        verbose_name="Используемые запасные части", unique=False, null=True, blank=True
    )
    restore_date = models.DateField(verbose_name="Дата восстановления")
    car = models.ForeignKey(
        to=Cars,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Машина",
    )
    service_company = models.ForeignKey(
        to=ServiceCompany,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Сервисная компания",
    )

    class Meta:
        db_table = "reclamation"
        verbose_name = "Рекламация"
        verbose_name_plural = "Рекламации"
        ordering = ("car",)

    def __str__(self):
        return f"{self.car} - {self.failure_node} - {self.service_company}"
    
    def get_absolute_url(self):
        return reverse("reclamation:reclamation_all")

    def equipment_downtime(self):
        self.delta = self.restore_date - self.date_of_refusal
        return f"{self.delta.days} суток"
        # return f"{self.restore_date - self.date_of_refusal}"

reclamation/forms.py
from dataclasses import fields
from django import forms

from cars.models import Cars
from deskbook.models import FailureNode, RecoveryMethod, ServiceCompany
from reclamation.models import Reclamation


class AddReclamationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        if "car_id" in kwargs:
            car_id = kwargs.pop("car_id")
            qs_car = Cars.objects.filter(id=car_id)
            sc_id = Cars.objects.filter(id=car_id).values_list('service_company', flat=True)[0]
            qs_sc = ServiceCompany.objects.filter(id=sc_id)
        else:
            qs_car = Cars.objects.all()
            qs_sc = ServiceCompany.objects.all()
        super(AddReclamationForm, self).__init__(*args, **kwargs)
        self.fields["car"].queryset = qs_car
        self.fields["service_company"].queryset = qs_sc
        
    class Meta:
        model = Reclamation
        fields = '__all__'

    date_of_refusal = forms.DateField(
        label="Дата отказа: ",
        widget=forms.DateInput(
            attrs={"placeholder": "Укажите дату", "class": "form-control auth-width"}
        ),
    )

    operating_hours = forms.IntegerField(
        label="Наработка, моточас: ",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Введите число",
                "class": "form-control auth-width",
            }
        ),
    )

    failure_node = forms.ModelChoiceField(
        queryset=FailureNode.objects.all(),
        label="Узел отказа: ",
        empty_label="Выберите узел",
        widget=forms.Select(attrs={"class": "form-select auth-width"}),
    )

    description_of_failure = forms.CharField(
        label="Описание отказа: ",
        required=False,
        widget=forms.Textarea(
            attrs={"placeholder": "Введите текст", "class": "form-control auth-width"}
        ),
    )

    recovery_method = forms.ModelChoiceField(
        queryset=RecoveryMethod.objects.all(),
        label="Способ восстановления: ",
        empty_label="Выберите способ",
        widget=forms.Select(attrs={"class": "form-select auth-width"}),
    )

    parts_used = forms.CharField(
        label="Используемые запасные части: ",
        required=False,
        widget=forms.Textarea(
            attrs={"placeholder": "Введите текст", "class": "form-control auth-width"}
        ),
    )

    restore_date = forms.DateField(
        label="Дата восстановления: ",
        widget=forms.DateInput(
            attrs={"placeholder": "Укажите дату", "class": "form-control auth-width"}
        ),
    )

    car = forms.ModelChoiceField(
        queryset=None,
        label="Машина: ",
        empty_label="Выберите машину",
        widget=forms.Select(attrs={"class": "form-select auth-width"}),
    )

    service_company = forms.ModelChoiceField(
        queryset=None,
        label="Сервисная компания: ",
        empty_label="Выберите компанию",
        widget=forms.Select(attrs={"class": "form-select auth-width"}),
    )
    

reclamation/views.py
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.paginator import EmptyPage, Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from cars.models import Cars
from reclamation.forms import AddReclamationForm
from reclamation.models import Reclamation


@permission_required('reclamation.view_reclamation', raise_exception=True)
def reclamation(request, failure_node_id=False, recovery_method_id=False, service_company_id=False):

    page = request.GET.get("page", 1)
    ordering = request.GET.get("order_by", None)
    user_role = request.user.user_role

    if user_role == 'CL':
        user_cars_list = Cars.objects.filter(client=request.user.id).values_list('id', flat=True)
        reclamation_limited = Reclamation.objects.filter(car__in=user_cars_list)
    elif user_role == 'SE':
        reclamation_limited = Reclamation.objects.filter(service_company=request.user.service_company_id)
    elif user_role == 'MG' or user_role == 'AD':
        reclamation_limited = Reclamation.objects.all()

    failure_node_for_filtration = reclamation_limited.values_list('failure_node', flat=True)
    recovery_method_for_filtration = reclamation_limited.values_list('recovery_method', flat=True)
    service_company_for_filtration = reclamation_limited.values_list('service_company', flat=True)

    if failure_node_id:
        user_reclamation = reclamation_limited.filter(failure_node=failure_node_id)
    elif recovery_method_id:
        user_reclamation = reclamation_limited.filter(recovery_method=recovery_method_id)
    elif service_company_id:
        user_reclamation = reclamation_limited.filter(service_company__id=service_company_id)
    else:
        user_reclamation = reclamation_limited
        
    if ordering and ordering != "default":
        user_reclamation = user_reclamation.order_by(ordering)

    paginator = Paginator(user_reclamation, 5)
    current_page = paginator.page(int(page))

    context = {
        'title': 'Рекламации',
        'reclamation': current_page,
        'fn_filter': failure_node_for_filtration,
        'rm_filter': recovery_method_for_filtration,
        'sc_filter': service_company_for_filtration,
    }
    return render(request, 'reclamation/reclamation_all.html', context)


@permission_required('reclamation.view_reclamation', raise_exception=True)
def get_reclamation(request, car_id, failure_node_id=False, recovery_method_id=False, service_company_id=False):

    car_item = Cars.objects.get(id=car_id)

    page = request.GET.get('page', 1)
    ordering = request.GET.get("order_by", None)

    if failure_node_id:
        reclamation_list = Reclamation.objects.filter(car__id=car_id).filter(failure_node=failure_node_id)
    elif recovery_method_id:
        reclamation_list = Reclamation.objects.filter(car__id=car_id).filter(recovery_method=recovery_method_id)
    elif service_company_id:
        reclamation_list = Reclamation.objects.filter(car__id=car_id).filter(service_company=service_company_id)    
    else:
        reclamation_list = Reclamation.objects.filter(car__id=car_id)

    failure_node_for_watch = reclamation_list.values_list('failure_node', flat=True)
    recovery_method_for_watch = reclamation_list.values_list('recovery_method', flat=True)
    service_company_for_watch = reclamation_list.values_list('service_company', flat=True)
    
    if ordering and ordering != "default":
        reclamation_list = reclamation_list.order_by(ordering)

    paginator = Paginator(reclamation_list, 2)
    try:
        current_page = paginator.page(int(page))
    except EmptyPage:
        current_page = paginator.page(int(page) - 1)

    context = {
        'title': 'Рекламации',
        "car": car_item, 
        'reclamations': current_page,
        'fn_for_watch': failure_node_for_watch,
        'rm_for_watch': recovery_method_for_watch,
        'sc_for_watch': service_company_for_watch,
    }

    return render(request, 'reclamation/reclamations.html', context)


@permission_required('reclamation.add_reclamation', raise_exception=True)
def add_reclamation(request, car_id=False):
    if request.method == "POST":
        restore_date_introduced = request.POST['restore_date']
        date_of_refusal_introduced = request.POST['date_of_refusal']
        
        if restore_date_introduced <= date_of_refusal_introduced:
            messages.warning(
                request, f"{request.user.username}, дата восстановления должна быть больше даты отказа!"
            )
            return redirect(request.META["HTTP_REFERER"])
        elif datetime.datetime.strptime(restore_date_introduced, '%d.%m.%Y') >= datetime.datetime.today():            
            messages.warning(
                request, f"{request.user.username}, дата восстановления должна быть меньше текущей даты!"
            )
            return redirect(request.META["HTTP_REFERER"])
        
        form = AddReclamationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, f"{request.user.username}, Вы успешно добавили рекламацию!"
            )
            if not car_id:
                return HttpResponseRedirect(reverse("reclamation:reclamation_all"))
            else:
                return HttpResponseRedirect(reverse("reclamation:car_reclamations", args=(car_id,)))
        else:
            messages.warning(
                request, f"{request.user.username}, Вы неверно ввели данные!"
            )
    elif request.method == "GET" and car_id:
        car = get_object_or_404(Cars, pk=car_id)
        sc_list = Cars.objects.filter(id=car_id).values_list('service_company', flat=True)[0]
        car_list = Cars.objects.filter(id=car_id).values('id')[0]['id']
        form = AddReclamationForm(initial={'car': car_list, 'service_company': sc_list}, car_id=car_id)
    else:
        form = AddReclamationForm()
        car = False

    context = {
        'title': 'Рекламации',
        'form': form,
        'car': car,
    }
    
    return render(request, 'reclamation/add_reclamation.html', context)


@permission_required('reclamation.change_reclamation', raise_exception=True)
def edit_reclamation(request, reclamation_id):
    item = get_object_or_404(Reclamation, id=reclamation_id)
    car_id = item.car.id
    car = get_object_or_404(Cars, id=car_id)

    if request.method == "POST":
        restore_date_introduced = request.POST['restore_date']
        date_of_refusal_introduced = request.POST['date_of_refusal']

        if datetime.datetime.strptime(restore_date_introduced, '%d.%m.%Y') <= datetime.datetime.strptime(date_of_refusal_introduced, '%d.%m.%Y'):
            messages.warning(
                request, f"{request.user.username}, дата восстановления должна быть больше даты отказа!"
            )
            return redirect(request.META["HTTP_REFERER"])
        elif datetime.datetime.strptime(restore_date_introduced, '%d.%m.%Y') >= datetime.datetime.today():            
            messages.warning(
                request, f"{request.user.username}, дата восстановления должна быть меньше текущей даты!"
            )
            return redirect(request.META["HTTP_REFERER"])
        
        form = AddReclamationForm(data=request.POST, instance=item)

        if form.is_valid():
            form.save()
            messages.success(
                request, f"{request.user.username}, Вы успешно изменили рекламацию {item}!"
            )
            return HttpResponseRedirect(reverse("reclamation:car_reclamations", args=(car_id,)))
        else:
            messages.warning(
                request, f"{request.user.username}, Вы неверно ввели данные!"
            )
    else:
        form = AddReclamationForm(instance=item)

    context = {
        'title': 'Рекламации',
        'form': form,
        'item': item,
        'car': car,
    }
    return render(request, 'reclamation/add_reclamation.html', context)


@permission_required('reclamation.delete_reclamation', raise_exception=True)
def remove_reclamation(request, reclamation_id):
    removable = Reclamation.objects.get(id=reclamation_id)
    removable.delete()
    messages.success(
        request, f"{request.user.username}, Вы успешно удалили рекламацию {removable}!"
    )
    try:
        return redirect(request.META["HTTP_REFERER"])
    except EmptyPage:
        return HttpResponseRedirect(reverse("reclamation:reclamation_all"))

reclamation/templates/includes/reclamationFiltrations.html
{% load static %}
{% load reclamation_tags %}

<!-- Форма сортировки -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Сортировка таблицы
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="?order_by=default">По умолчанию</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item fontSizeBtn" href="?order_by=date_of_refusal">По возрастанию даты отказа</a></li>
        <li><a class="dropdown-item fontSizeBtn" href="?order_by=-date_of_refusal">По убыванию даты отказа</a></li>    
    </ul>
</div>

<!-- Фильтрация по узел отказа -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Узел отказа
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="{% url "reclamation:reclamation_all" %}">Все узлы</a></li>
        <li><hr class="dropdown-divider"></li>
        {% tag_failure_node as failure_node %}
        {% for node in failure_node %}
        {% if node.id in fn_filter %}
            <li>
                <a class="dropdown-item fontSizeBtn" href="{% url "reclamation:failure_node" node.id %}">
                    {{ node.name }}
                </a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

<!-- Фильтрация по способ восстановления -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Cпособ восстановления
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="{% url "reclamation:reclamation_all" %}">Все узлы</a></li>
        <li><hr class="dropdown-divider"></li>
        {% tag_recovery_method as recovery_method %}
        {% for method in recovery_method %}
        {% if method.id in rm_filter %}
            <li>
                <a class="dropdown-item fontSizeBtn" href="{% url "reclamation:recovery_method" method.id %}">
                    {{ method.name }}
                </a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

<!-- Фильтрация по сервисная компания -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Cервисная компания
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="{% url "reclamation:reclamation_all" %}">Все узлы</a></li>
        <li><hr class="dropdown-divider"></li>
        {% tag_service_company as service_company %}
        {% for company in service_company %}
        {% if company.id in sc_filter %}
            <li>
                <a class="dropdown-item fontSizeBtn" href="{% url "reclamation:service_company" company.id %}">
                    {{ company.name }}
                </a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>
{% if perms.reclamation.add_reclamation %}
    <button class="btn btn-primary btn-sm mb-2 ms-auto" type="button" onclick="window.location.href='{% url "reclamation:add_reclamation" %}'; return false">
        <img class="mx-1" src="{% static "source/icons/clipboard-x-fill.svg" %}" alt="add" width="16" height="16">
        Добавить рекламацию
    </button>
{% endif %}

reclamation/templates/includes/reclamationFiltrations_item.html
{% load static %}
{% load reclamation_tags %}

<!-- Форма сортировки -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Сортировка таблицы
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="?order_by=default">По умолчанию</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item fontSizeBtn" href="?order_by=date_of_refusal">По возрастанию даты отказа</a></li>
        <li><a class="dropdown-item fontSizeBtn" href="?order_by=-date_of_refusal">По убыванию даты отказа</a></li>    
    </ul>
</div>

<!-- Фильтрация по узел отказа -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Узел отказа
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="{% url "reclamation:car_reclamations" car.id %}">Все узлы</a></li>
        <li><hr class="dropdown-divider"></li>
        {% tag_failure_node as failure_node %}
        {% for node in failure_node %}
        {% if node.id in fn_for_watch %}
            <li>
                <a class="dropdown-item fontSizeBtn" 
                href="{% url "reclamation:car_reclamations_failure_node" car.id node.id %}">
                    {{ node.name }}
                </a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

<!-- Фильтрация по способ восстановления -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Cпособ восстановления
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="{% url "reclamation:car_reclamations" car.id %}">Все узлы</a></li>
        <li><hr class="dropdown-divider"></li>
        {% tag_recovery_method as recovery_method %}
        {% for method in recovery_method %}
        {% if method.id in rm_for_watch %}
            <li>
                <a class="dropdown-item fontSizeBtn" 
                href="{% url "reclamation:car_reclamations_recovery_method" car.id method.id %}">
                    {{ method.name }}
                </a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

<!-- Фильтрация по сервисная компания -->
<div class="dropdown mb-2 me-1">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Cервисная компания
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item fontSizeBtn" href="{% url "reclamation:car_reclamations" car.id %}">Все узлы</a></li>
        <li><hr class="dropdown-divider"></li>
        {% tag_service_company as service_company %}
        {% for company in service_company %}
        {% if company.id in sc_for_watch %}
            <li>
                <a class="dropdown-item fontSizeBtn" href="{% url "reclamation:car_reclamations_service_company" car.id company.id %}">
                    {{ company.name }}
                </a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

{% if perms.reclamation.add_reclamation %}
    <button class="btn btn-primary btn-sm mb-2 ms-auto" type="button" onclick="window.location.href='{% url "reclamation:add_reclamation_car" car.id %}'; return false">
        <img class="mx-1" src="{% static "source/icons/clipboard-x-fill.svg" %}" alt="add" width="16" height="16">
        Добавить рекламацию
    </button>
{% endif %}